// <auto-generated />
namespace ZeroHunger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DistributeTableAddedRelationlinked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DistributeTableAddedRelationlinked));
        
        string IMigrationMetadata.Id
        {
            get { return "202303191814319_Distribute-Table-Added&Relation-linked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
